// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVMSSEhw_Qnq0MmwXgcbqyjC0_Q-C6wQQ',
    appId: '1:141684838971:web:e6d90e47ec8d33e0bec21e',
    messagingSenderId: '141684838971',
    projectId: 'app-mov3-d3673',
    authDomain: 'app-mov3-d3673.firebaseapp.com',
    databaseURL: 'https://app-mov3-d3673-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov3-d3673.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjerVlNGKIKd2i4e-BN8j13TJTnKUAvwU',
    appId: '1:141684838971:android:e0be847a361aad2dbec21e',
    messagingSenderId: '141684838971',
    projectId: 'app-mov3-d3673',
    databaseURL: 'https://app-mov3-d3673-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov3-d3673.firebasestorage.app',
  );

}